### ISSUE TITLE
Broken links for 1.1.1

### ISSUE THREAD

**Issue by mylastgg** [mixpanel/mixpanel-unity#37]
If I try to download the new 1.1.1 version every link pointing to that version is broken and leads to a 404 (download link and change log alike):

https://github.com/mixpanel/mixpanel-unity/releases/tag/v1.1.1

**Comment by argenisf** [comment]
Hey @mylastgg , Argenis from the support team here. Sorry for the confusion there. We had released an update last week, but decided to pull it since it still had an issue. As of know, the latest available release is 1.1.0, but we should be releasing an update soon, hopefully today, so if possible, I would hold on for that one.

**Comment by mylastgg** [comment]
Got it! I'll be waiting for 1.1.1 then 👍
