### ISSUE TITLE
.NET 3.5 compatibility

### ISSUE THREAD

**Issue by nanox77** [mixpanel/mixpanel-unity#92]
Hi guys, i need to use Mixpanel-unity with .net 3.5 but I'm facing a lot of issues because It looks like the library is using many features from C# 6.0+

Are there any possibility to support .NET 3.5? Or is there any older mixpanel-unity version that supports it?

Thank you

**Comment by patedit** [comment]
Hi @nanox77 - As in 2.1.1, our library is compatible with .NET 4.x equivalent. What Unity version are you using, out of curiosity?
Would it be possible to change your scripting runtime version to be 4.x equivalent?

Otherwise, you can find the latest release that is compatible with .net 3.5 here: https://github.com/mixpanel/mixpanel-unity/releases/tag/v1.3.1

**Comment by nanox77** [comment]
I'm using Unity 2018.4.x but project was created with .NET 3.5 😞. Is almost impossible change our scripting runtime version to be 4.x for now. I could fork and change mixpanel-unity code to support .NET 3.5 .
However, now i will try to use v1.3.1 in order to make it work and in near future change our scripting version to be 4.x. 

Version 1.3.1 is compatible with current Mixpanel Dashboard?

Thanks!

**Comment by patedit** [comment]
Sorry for the inconvenience. Notice that v1.3.1 is no longer supported (aka won't be maintained) but it works perfectly - we have many clients still on v1.3.1.

If you decide to fork our library, a PR would be greatly appreciated. There are around 208 errors due to the usage of new features included in c# 7.0 so it's a matter of addressing one by one.

Since .NET 4 should be backwards compatible with 3.5, what problems are you facing if you change the version runtime? I understand there could be some issues due to how the framework now works, but I have not faced any personally. Any hints would be also appreciated. Thanks!

**Comment by nanox77** [comment]
Changing to be .NET 4.x i will have problem with other dependencies which are in .NET 3.5 like UniRx and many plugins made by us.
I can see two ways: fork or use v1.3.1. I will analyze which is best choice. 
Of course, i would a PR if i choose fork it.

Thank you a lot for support!

**Comment by patedit** [comment]
No problem! You can find the unitypackage of 1.3.1 here: https://github.com/mixpanel/mixpanel-unity/releases/download/v1.3.1/MixpanelSDK-v1.3.1.unitypackage

Good luck!

**Comment by nanox77** [comment]
We decided to use v1.3.1 for now. In the future we will try to upgrade our app to be .NET 4.5.

Thank you!
